app:
  name: spp
log:
  level: INFO

database:
  name: spp
#  username: ${DATABASE_USERNAME}
  username: ${{HOME}}
  password: ${DATABASE_PASSWORD}
  host: ${DATABASE_HOST}
  port: 3306
  dialect: mysql
  driver: pymysql


