app:
  name: spp
log:
  level: INFO

database:
  name: spp
  username: issa
  password: Iss4K4m001?
  host: ec2-54-93-89-186.eu-central-1.compute.amazonaws.com
  port: 3306
  dialect: mysql
  driver: pymysql


